  services:
    # ---- 7Days to die servers + Mumble voip server ----
      7dtd:
        image: my-7dtd-server
        platform: linux/amd64
        container_name: 7dtd
        environment:
          - TZ=${TZ}
        volumes:
          - ${ROOT}/config/7dtd:/home/steam/7dtd
        ports:
          - 26900:26900/tcp
          - 26900:26900/udp
          - 26901:26901/udp
          - 26902:26902/udp
          - 8080:8080/tcp   # Web dashboard
          - 8081:8081/tcp   # Telnet
        restart: unless-stopped



    # 7dtdserver2:
    #       image: didstopia/7dtd-server
    #       platform: linux/amd64
    #       container_name: 7dtd
    #       environment:
    #         - START_MODE=1
    #         - PUID=1000
    #         - PGID=1000
    #         - TZ=${TZ}
    #         - TEST_ALERT=YES
    #         - ALLOC_FIXES=YES
    #         - STEAMCMD_FORCE_PLATFORM_TYPE=64   # <-- IMPORTANT FIX
    #       volumes:
    #         - ${ROOT}/config/7dtd:/app/.local/share
    #         - ${ROOT}/config/steamcmd:/steamcmd/7dtd
    #       ports:
    #         - 26900:26900/tcp
    #         - 26900:26900/udp
    #         - 26901:26901/udp
    #         - 26902:26902/udp
    #         - 8080:8080/tcp
    #         - 8081:8081/tcp
    #         - 8082:8082/tcp
    #       restart: unless-stopped


    # mumble-server:
    #   image: mumblevoip/mumble-server:latest
    #   container_name: PlayTime-mumble-server
    #   hostname: mumble-server
    #   restart: on-failure
    #   ports:
    #     - 64738:64738
    #     - 64738:64738/udp
# # Minecraft Servers
    # minecraft-bedrock-server:
    #   image: itzg/minecraft-bedrock-server
    #   container_name: PlayTime-mc
    #   environment:
    #     - 'EULA=TRUE'
    #     - 'SERVER_PORT=19132'
    #     - 'DIFFICULTY=peaceful'
    #     - 'PUID=${PUID}'
    #     - 'PGID=${PGID}'
    #     - 'TZ=${TZ}'
    #     - 'VERSION=1.21.114.1'
    #     # - LEVEL_SEED= optional seed for generating your world
    #   ports:
    #     - "19132:19132/udp"
    #   volumes:
    #     - '${ROOT}/config/bedrock:/data'
    #   stdin_open: true
    #   tty: true